# Generated by Django 4.2.5 on 2023-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_lower',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='name_lower',
            field=models.CharField(default='', max_length=255),
        ),
    ]
