# Generated by Django 4.2.5 on 2023-09-27 15:43

from django.db import migrations, models
import project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=project.utils.datetime_now, editable=False)),
                ('answered_at', models.DateTimeField(null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
